services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn jigyasa_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jigyasa_backend.settings
      - key: SECRET_KEY
        generateValue: true